kubeflow/kubebench

kubebench/kubebench-job/kubebench-job.libsonnet, kubebench/kubebench-job/parts.yaml, kubebench/kubebench-job/prototypes/kubebench-job.jsonnet, kubebench/registry.yaml
This adds a ksonnet package for kubebench with basic workflow.
=> Add ksonnet package with basic benchmark workflow

images/benchmark_harness/runner_cpu.Dockerfile, images/common/configurator.Dockerfile, images/common/configurator/manifest_generator.py, images/common/configurator/requirements.txt, images/common/configurator/tf-job.jsonnet, images/common/configurator/tf-job.libsonnet
=> Add basic images needed by kubebench workflow

examples/poc_benchmark_harness/benchmark_config.yaml, examples/poc_benchmark_harness/example_params.libsonnet, examples/poc_benchmark_harness/job_config.yaml, examples/poc_benchmark_harness/schema.txt
=> Add initial POC example

components/tf_cnn_benchmarks/log_reporter.Dockerfile, components/tf_cnn_benchmarks/log_reporter.py
This fixes a bug in dockerfile in PR #28.
=> Fix log reporter

README.md
=> Add initial version of getting started guide

README.md
/assign @xyhuang 
Signed-off-by: Ce Gao <gaoce@caicloud.io>
=> README: Add design doc

OWNERS
Adding myself to reviewers.
/assign @xyhuang 
Signed-off-by: Ce Gao <gaoce@caicloud.io>
=> OWNERS: Add gaocegege

OWNERS
adding as reviewer as suggested by xyhuang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/58)
=> adding as reviewer

kubebench/nfs-server/nfs-server.libsonnet, kubebench/nfs-server/parts.yaml, kubebench/nfs-server/prototypes/nfs-server.jsonnet, kubebench/nfs-volume/nfs-volume.libsonnet, kubebench/nfs-volume/parts.yaml, kubebench/nfs-volume/prototypes/nfs-volume.jsonnet, kubebench/registry.yaml, test/py/kubebench/test/deploy_kubeflow.py, test/py/kubebench/test/deploy_utils.py, test/py/kubebench/test/test_kubebench_job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/59)
=> adding a smoke test #46

README.md, components/common/configurator/tf-job.jsonnet, test/py/kubebench/test/test_kubebench_job.py
Fix #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/65)
=> Fix argument order in configurator's tf-job.jsonnet

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/68)
=> add swiftdiaries to approvers list

.travis.yml, Makefile, OWNERS, README.md, hack/verify-gofmt.sh
Adds travis and a Makefile (run `$ make verify`) to check for gofmt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/72)
=> Adds gofmt check.

build/images/controller/Dockerfile, controller/misc/fake_kubeconfig
Fix #69 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/75)
=> Add dockerfile for controller

build/images/examples/tf-cnn/post_processor.Dockerfile, build/images/examples/tf-cnn/runner_cpu.Dockerfile, build/images/examples/tf-cnn/runner_gpu.Dockerfile, examples/config/tf-cnn/tf-cnn-dummy.yaml, examples/src/tf-cnn/post_processor.py, examples/src/tf-cnn/runner.py, kubebench/kubebench-examples/parts.yaml, kubebench/kubebench-examples/prototypes/tf-cnn.jsonnet, kubebench/registry.yaml
- Add kubebench-example ksonnet package and tf-cnn prototypes
- Add tf-cnn source codes and dockerfiles
fix #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/78)
=> Add refactored tf-cnn example workload

build/images/controller/Dockerfile
This patch includes the followings:
- Fix package installation with apk --update
- Add controller binaries to $PATH
- Remove unnecessary entrypoint
Fix #87 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/84)
=> Fix and improve controller image

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/101)
=> Update readme with the latest changes

README.md, scripts/install_quickstarter.sh, scripts/uninstall_quickstarter.sh
This adds installation and uninstallation scripts for quickstarter, and improves/fixes the readme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/105)
=> Add quickstarter installation/uninstallation scripts

kubebench/kubebench-job/kubebench-job.libsonnet, kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
This improves the ksonnet package of kubebench-job:
- use camelCase for parameters and improved some parameter names
- fix bugs in secret parameters
- make csv reporter args explicit through parameters
- improved workflow step names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/103)
=> Improve kubebench-job ksonnet package

kubebench/kubebench-quickstarter/kubebench-quickstarter-service.libsonnet
This improves the nfs file server with an apache http server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/111)
=> Improve quick starter file server

README.md, scripts/install_quickstarter.sh
Fixes https://github.com/kubeflow/kubebench/issues/112.
I added k8s namespace in installation script and improve README file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/113)
=> Add namespace to installation script

prow_config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/118)
=> fix prow config for postsubmit

build/images/controller/build_image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/120)
=> Disable CGO in go build

build/images/examples/tf-cnn/runner-gpu.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/129)
=> set LD_LIBRARY_PATH correctly in gpu image

test/py/kubebench/test/deploy_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/159)
=> Fix ks packages in test

README.md, kubebench/registry.yaml
Try to address #164. Fix documentation and also remove legacy packages in kubebench registry. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/165)
=> Cleanup legacy ksonnet packages

test/py/kubebench/test/deploy_kubeflow.py, test/workflows/components/workflows.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/169)
=> Update e2e test to sync with upstream kubeflow changes

README.md, examples/src/mpi/README.md
Follow up on @xyhuang advice from #167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/168)
=> Add documentation for MPI benchmark job

Gopkg.lock, Gopkg.toml, vendor/github.com/golang/groupcache/LICENSE, vendor/github.com/golang/groupcache/lru/lru.go, vendor/k8s.io/client-go/tools/record/doc.go, vendor/k8s.io/client-go/tools/record/event.go, vendor/k8s.io/client-go/tools/record/events_cache.go, vendor/k8s.io/client-go/tools/record/fake.go
This updates the dependencies for follow-up changes in v1alpha2 API design.
Partially addresses #173 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/178)
=> Update dependencies for v1alpha2 API changes

build/images/workflow-agent/Dockerfile, build/images/workflow-agent/build_image.sh
This is to replace the old "controller" builds.
Partially addresses #173 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/184)
=> Add build scripts for workflow agent

controller/cmd/cli/kubebench-workflow-builder/app/defaultconfig.go, controller/cmd/cli/kubebench-workflow-builder/app/options.go, controller/cmd/cli/kubebench-workflow-builder/app/workflowbuilder.go, controller/cmd/cli/kubebench-workflow-builder/main.go
This adds a CLI tool for building argo workflow from kubebenchjob.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/186)
=> Add CLI tool for workflow builder

examples/config/tf-cnn/tf-cnn-dummy.yaml, kubebench/kubebench-examples/prototypes/tf-cnn.jsonnet
update the runner image to public image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/187)
=> update the runner image to public image

test/py/kubebench/test/deploy_kubeflow.py, test/py/kubebench/test/deploy_utils.py, test/workflows/app.yaml, test/workflows/components/workflows.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/208)
=> Fix test workflow

build/images/examples/tf-cnn/runner-cpu.Dockerfile, build/images/examples/tf-cnn/runner-gpu.Dockerfile, examples/src/tf-cnn/post_processor.py, examples/src/tf-cnn/runner.py
- now compatible with tensorflow 1.13
- no more kubebench environment variables in code
- update dockerfiles and fix build issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kubebench/210)
=> Update tf-cnn example
